
CREATE DATABASE NOX;
USE NOX;
CREATE TABLE USERS(
	id MEDIUMINT AUTO_INCREMENT,
	NAME CHAR(255),
	EMAIL CHAR(255),
	PHONE CHAR(255),
	PASSWORD CHAR(255),
	PRIMARY KEY(id)
);
CREATE TABLE MESSAGE(
	id MEDIUMINT AUTO_INCREMENT,
	ID_OUT char(255),
	ID_PUT char(255),
	MESSAGE CHAR(255),
	PRIMARY KEY(id)
);
